### ISSUE TITLE
Closing the session calls wrong endpoint

### ISSUE THREAD

**Issue by martyn82** [fabaff/python-connect-box#17]
Hi @fabaff, first of all, I'm a fan of your connectbox module!

I noticed, however, that there's a small bug in which the session stays open. When using your module, this results in not being able to access the connectbox GUI from a browser anymore, because there's already an active session.

It seems the problem is that for the CMD_LOGOUT command, the `/xml/getter.xml` path is requested, where it should be the `/xml/setter.xml`.

**Comment by pvizeli** [comment]
We should use https://github.com/ties/compal_CH7465LG_py on HA. This library is also from a HA member
